/*

--drop table if exists market.databasechangelog;
--drop table if exists market.databasechangeloglock;

-- account
drop table if exists account_schema.accounts;
drop table if exists account_schema.outbox;
drop schema if exists account_schema;

-- cash
drop table if exists cash_schema.outbox;
drop schema if exists cash_schema;

-- transfer
drop table if exists transfer_schema.outbox;
drop schema if exists transfer_schema;

*/

create schema if not exists "account_schema";
set schema 'account_schema';

create table if not exists "accounts" (
    "id"                bigint          generated by default as identity,
    "login"             varchar         not null,
    "name"              varchar         not null,
    "birthdate"         date            not null,
    -- account_balances
    "balance_amount"    int             not null,
    --
    constraint pk_accounts primary key ("id"),
    constraint uk_accounts unique ("login")
);

create table if not exists "outbox" (
    "id"            bigint          generated by default as identity,
    "src"           varchar         not null,
    "login"         varchar         not null,
    "created_at"    timestamp       not null,
    "body"          varchar         not null,
    --
    constraint "pk_outbox" primary key ("id")
);

insert into accounts("login", "name", "birthdate", "balance_amount")
with src as (
    values
        ('user',  'Name1', DATE'2001-01-01', 100),
        ('user2', 'Name2', DATE'2001-01-02', 200),
        ('user3', 'Name3', DATE'2001-01-03', 300)
)
select * from src where not exists(select 1 from "accounts" limit 1);




--- CASH ---

create schema if not exists "cash_schema";

set schema 'cash_schema';

create table if not exists "outbox" (
    "id"            bigint          generated by default as identity,
    "src"           varchar         not null,
    "login"         varchar         not null,
    "created_at"    timestamp       not null,
    "body"          varchar         not null,
    --
    constraint "pk_outbox" primary key ("id")
);

--- TRANSFER ---

create schema if not exists "transfer_schema";

set schema 'transfer_schema';

create table if not exists "outbox" (
    "id"            bigint          generated by default as identity,
    "src"           varchar         not null,
    "login"         varchar         not null,
    "created_at"    timestamp       not null,
    "body"          varchar         not null,
    --
    constraint "pk_outbox" primary key ("id")
);