create table if not exists "outbox" (
    "id"            bigint          generated by default as identity,
    "src"           varchar         not null,
    "login"         varchar         not null,
    "created_at"    timestamp       not null,
    "body"          varchar         not null,
    --
    constraint "pk_outbox" primary key ("id")
);