server:
  port: 8081
spring:
  application:
    name: gateway
  config:
    import: configserver:http://127.0.0.1:8888

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG