spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${FRON_UI_KEYCLOAK_CLIENT_ID:front-ui}
            client-secret: ${FRON_UI_KEYCLOAK_CLIENT_SECRET:front-ui-secret}
            authorization-grant-type: authorization_code
            scope: openid,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak