spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-route  # ID роута
              #uri: lb://accounts-service  # URI микросервиса, на который следует перенаправлять запрос
              #uri: http://localhost:8085
              uri: lb://account
              predicates:
                - Path=/account/** # URI поступающего в Gateway запроса, с которым мэтчится роут
              filters:
                - RewritePath=/account/?(?<segment>.*), /$\{segment} # Фильтр, который модифицирует запрос к целевому сервису (убирается имя сервиса в начале)
            - id: cash-route
              uri: lb://cash
              predicates:
                - Path=/cash/**
              filters:
                - RewritePath=/cash/?(?<segment>.*), /$\{segment}
            - id: transfer-route
              uri: lb://transfer
              predicates:
                - Path=/transfer/**
              filters:
                - RewritePath=/transfer/?(?<segment>.*), /$\{segment}