spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: ${SPRING_KEYCLOAK_REALM_URL:http://localhost:8180/realms/bank-realm}
          #authorization-uri: http://localhost:8180/realms/bank-realm/protocol/openid-connect/auth
          token-uri: ${SPRING_KEYCLOAK_REALM_URL:http://localhost:8180/realms/bank-realm}/protocol/openid-connect/token
          user-info-uri: ${SPRING_KEYCLOAK_REALM_URL:http://localhost:8180/realms/bank-realm}/protocol/openid-connect/userinfo
          jwk-set-uri: ${SPRING_KEYCLOAK_REALM_URL:http://localhost:8180/realms/bank-realm}/protocol/openid-connect/certs

      client:
        registration:
          transfer-service:
            provider: keycloak
            client-id: transfer-service
            client-secret: transfer-service-secret
            authorization-grant-type: client_credentials
            #scope: openid,profile,SERVICE,ACCOUNTS_WRITE
        provider:
          keycloak:
            issuer-uri: ${SPRING_KEYCLOAK_REALM_URL:http://localhost:8180/realms/bank-realm}
            user-name-attribute: preferred_username
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/my_bank}?currentSchema=transfer_schema
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver