eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

spring:
  application:
    name: front-ui
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: spring-cloud-config-server
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${FRON_UI_KEYCLOAK_CLIENT_ID:front-ui}
            client-secret: ${FRON_UI_KEYCLOAK_CLIENT_SECRET:front-ui-secret}
            authorization-grant-type: authorization_code
            scope: openid,profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak

server:
  port: 8080

