spring.application.name=my-bank-front-app

server.port=8080

spring.security.oauth2.client.registration.keycloak.client-id=front-ui
spring.security.oauth2.client.registration.keycloak.client-secret=${FRON_UI_KEYCLOAK_SECRET:front-ui-secret}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.keycloak.provider=keycloak

#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/bank-realm
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8180/realms/bank-realm/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=${SPRING_KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/bank-realm}/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=${SPRING_KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/bank-realm}/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${SPRING_KEYCLOAK_ISSUER_URI:http://localhost:8180/realms/bank-realm}/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

# logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.web=DEBUG