create table if not exists "accounts" (
    "id"              bigint          generated by default as identity,
    "login"           varchar         not null,
    "full_name"       varchar         not null,
    "birthdate"       date            not null,
    -- account_balances
    "balance_amount"  bigint          not null,
    --
    constraint pk_items primary key ("id"),
    constraint uk_items unique ("login")
);