create table if not exists "accounts" (
    "id"                bigint          generated by default as identity,
    "login"             varchar         not null,
    "name"              varchar         not null,
    "birthdate"         date            not null,
    -- account_balances
    "balance_amount"    int             not null,
    --
    constraint pk_items primary key ("id"),
    constraint uk_items unique ("login")
);

create table if not exists "outbox" (
    "id"            bigint          generated by default as identity,
    "src"           varchar         not null,
    "login"         varchar         not null,
    "created_at"    timestamp       not null,
    "body"          varchar         not null,
    --
    constraint "pk_outbox" primary key ("id")
);